# Generated by Django 4.2 on 2023-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='', max_length=600),
        ),
    ]
